# Generated by Django 2.2 on 2023-09-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0004_departmentmodel_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
