# Generated by Django 2.2 on 2023-09-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensemodel',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
