# Generated by Django 2.2 on 2023-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_expense', '0002_auto_20230918_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='amount',
            new_name='claimed_amount',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='claim_date',
            new_name='claimed_date',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
