# Generated by Django 2.2 on 2023-09-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_expense', '0003_auto_20230918_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='receipt_image',
            field=models.ImageField(default=None, upload_to='receipt/'),
        ),
    ]
