# Generated by Django 2.2 on 2023-09-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='educational_requirements',
        ),
    ]
