# Generated by Django 2.2 on 2023-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_job', '0003_auto_20230908_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='application_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
