# Generated by Django 2.2 on 2023-09-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0003_auto_20230911_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='project_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ongoing Project Name'),
        ),
    ]
