# Generated by Django 2.2 on 2023-09-08 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_job', '0002_remove_jobmodel_educational_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='company_name',
            field=models.CharField(default='yaehrms', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
