# Generated by Django 2.2 on 2023-09-08 17:52

from django.db import migrations, models
import hr_job.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_job', '0005_auto_20230909_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='published_date',
            field=models.DateTimeField(default=hr_job.models.today),
        ),
    ]
