# Generated by Django 2.2 on 2023-09-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_job', '0006_auto_20230909_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='additional_information',
            field=models.TextField(blank=True, default='Additional Information', null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='benefits',
            field=models.TextField(blank=True, default='Meal allowance, Ferry, Bonus', null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='contact_name',
            field=models.CharField(blank=True, default='HR Department', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='employment_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], default='Full-Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='location',
            field=models.CharField(default='Yangon', max_length=200),
        ),
    ]
