# Generated by Django 2.2 on 2023-09-13 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sequence', models.IntegerField(default='1')),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('resume', models.FileField(upload_to='resume/')),
                ('interview_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('interview_location', models.CharField(blank=True, max_length=200, null=True)),
                ('interview_feedback', models.TextField(blank=True, null=True)),
                ('assessment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assessment_feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='submitted', max_length=20)),
                ('note', models.TextField(max_length=100, verbose_name='Note')),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer_extended', models.BooleanField(default=False)),
                ('offer_accepted', models.BooleanField(default=False)),
                ('offer_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_benefits', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
