# Generated by Django 2.2 on 2023-09-06 09:33

from django.db import migrations, models
import django.utils.timezone
import hr_contract.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=50, verbose_name='Contract Name')),
                ('contract_id', models.CharField(max_length=30, unique=True, verbose_name='Contract ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(default=hr_contract.models.next_year, verbose_name='End Date')),
                ('contract_type', models.CharField(max_length=30)),
                ('rank', models.IntegerField(default=1, verbose_name='Rank')),
                ('terminated_date', models.DateField(blank=True)),
                ('terminated_reason', models.TextField(blank=True)),
                ('status', models.CharField(default='Draft', max_length=20, verbose_name='Status')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, max_length=200, verbose_name='Note')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='contract/', verbose_name='Attachment')),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, default=2000, max_digits=10)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=2000, max_digits=10)),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=3000, max_digits=10)),
                ('allowed_annual_leave', models.IntegerField(blank=True, default=12)),
                ('contractor_name', models.CharField(blank=True, max_length=100, verbose_name='Contractor Name')),
                ('sub_contractor_name', models.CharField(blank=True, max_length=100, verbose_name='Sub-Contractor Name')),
            ],
        ),
    ]
