# Generated by Django 2.2 on 2023-09-08 17:51

import datetime
from django.db import migrations, models
import hr_job.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_job', '0004_auto_20230908_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='application_deadline',
            field=models.DateField(default=hr_job.models.next2months),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 0, 21, 10, 580993)),
        ),
    ]
