# Generated by Django 2.2 on 2023-09-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee', '0002_auto_20230907_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='picture',
            field=models.ImageField(blank=True, default='default', upload_to='employee/', verbose_name='Picture'),
        ),
    ]
