# Generated by Django 2.2 on 2023-09-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee', '0003_auto_20230920_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='employee/', verbose_name='Picture'),
        ),
    ]
