# Generated by Django 2.2 on 2023-09-11 09:10

from django.db import migrations, models
import hr_department.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deadline',
            field=models.DateTimeField(blank=True, default=hr_department.models.next_year, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(default='Running Project', max_length=10, verbose_name='Status'),
        ),
    ]
