# Generated by Django 2.2 on 2023-09-11 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0005_auto_20230911_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='updated_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
